# Generated by Django 5.1.7 on 2025-03-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newscategory_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
