# Generated by Django 5.1.7 on 2025-03-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newscategory_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news24_media/default.jpg', upload_to='news24_media/'),
        ),
    ]
