# Generated by Django 5.1.7 on 2025-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
