# Generated by Django 5.1.7 on 2025-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_news_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='card_image',
            field=models.ImageField(default='news24_media/cards/default.jpg', upload_to='news24_media/cards/'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='news24_media/news/default.jpg', upload_to='news24_media/news/'),
        ),
    ]
