# Generated by Django 5.1.7 on 2025-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_news_image_news_card_image_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='card_image',
            field=models.ImageField(default='cards/default.jpg', upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='news/default.jpg', upload_to='news/'),
        ),
    ]
