# Generated by Django 5.1.7 on 2025-03-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_card_image_alter_news_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured_type',
            field=models.CharField(choices=[('main', 'Main Featured'), ('side', 'Side Featured'), ('none', 'Not Featured')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
