# Generated by Django 5.1.7 on 2025-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
