"""
Django settings for news24 project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rmy1bbs5gs-6)6j8us1z9_o8-=r$ifvltkmb!h=ixq0(phe%ch'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'news24.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'core.context_processors.menu_pages',
                'core.context_processors.social_media',
                'core.context_processors.categories_pages',
                'core.context_processors.ads_processor',
                'core.context_processors.contact_ways'
            ],
        },
    },
]

WSGI_APPLICATION = 'news24.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




MEDIA_URL = '/news24_media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'news24_media')


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



HOME_URL =  'http://localhost:8000/'
SPORTS_URL =  'http://localhost:8000/sports'
TECH_URL =  'http://localhost:8000/tech'
BUSINESS_URL =  'http://localhost:8000/business'
FASHION_URL =  'http://localhost:8000/fashion'
POLITICS_URL =  'http://localhost:8000/politics'
CONTACT_URL =  'http://localhost:8000/contact'

INSTAGRAM_URL = 'https://www.instagram.com/?locale=az_AZ'
TWITTER_URL = 'https://twitter.com/yourusername'
FACEBOOK_URL = 'https://www.facebook.com/?locale=az_AZ'
LINKEDIN_URL = 'https://www.linkedin.com/'
YOUTUBE_URL = 'https://www.youtube.com/'

ENTERTAINMENT_URL = 'http://localhost:8000/entertainment'
NATIONAL_URL = 'http://localhost:8000/national'
INTERNATIONAL_URL = 'http://localhost:8000/international'
ECONOMICS_URL = 'http://localhost:8000/economics'
TRADES_URL = 'http://localhost:8000/trades'


CALL_URL = 'tel:+994501234567'
MAIL_URL = 'https://mail.google.com/mail/?view=cm&fs=1&to=vafakhanim.h@gmail.com'
LOCATION_URL  =  'https://maps.app.goo.gl/P8KWm1UEGHDSKzjG9'


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "vfa.xh05@gmail.com"
EMAIL_HOST_PASSWORD = "rzpd lekt iulu veaz"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER